# Joint State Controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# Group Velocity Controller
arm140_group_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

# Joint Trajectory Controller
arm140_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  
  gains: 
    joint_1: {p: 100.0,  d: 1.0, i: 5.0, i_clamp: 1}
    joint_2: {p: 500.0,  d: 1.0, i: 10.0}
    joint_3: {p: 300.0,  d: 1.0, i: 10.0}
    joint_4: {p: 100.0, d: 0.1, i: 3.0}
    joint_5: {p: 100.0,  d: 0.1, i: 3.0}
    joint_6: {p: 100.0,  d: 0.1, i: 1.0}
    
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.1, goal: 0.1}
    joint_2: {trajectory: 0.1, goal: 0.1}
    joint_3: {trajectory: 0.1, goal: 0.1}
    joint_4: {trajectory: 0.1, goal: 0.1}
    joint_5: {trajectory: 0.1, goal: 0.1}
    joint_6: {trajectory: 0.1, goal: 0.1}
  
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
